version: 2

updates:
  # NuGet packages
  - package-ecosystem: nuget
    directory: "/PizzaOrderingSystemC#"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
